[build]
builder = "DOCKERFILE"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
numReplicas = 1
healthcheckPath = "/admin/login/"
healthcheckTimeout = 300

# Set environment variables
[envs]
PORT = "8000"
DJANGO_SETTINGS_MODULE = "resumecraft.settings"
SECRET_KEY = "${SECRET_KEY}"
