[build]
builder = "DOCKERFILE"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1
healthcheckPath = "/health/"
healthcheckTimeout = 10
skipHealthcheck = false

# Set environment variables
[envs]
PORT = "8000"
DJANGO_SETTINGS_MODULE = "resumecraft.settings"
DEBUG = "True"
SECRET_KEY = "${SECRET_KEY}"
